default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: seeks_development

test:
  <<: *default
  database: seeks_test

production:
  <<: *default
  database: seeks_production
  username: ubuntu
  password: <%= ENV['SEEKS_DATABASE_PASSWORD'] %>
